#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Jul  9 09:24:20 2019

@author: irebollo
"""

"""
Basic Visualization
===================

Initialize a basic visualization session.

"""

from surfer import Brain
from mayavi import mlab
import numpy as np
from surfer import io
import mne
import os

"""
Define the three important variables.
Note that these are the first three positional arguments
in tksurfer (and pysurfer for that matter).
"""


subject_id = 'fsaverage'
surf = 'inflated'
subjects_dir="/media/irebollo/storage/projects/Navigastric/freesurferData/"

LOS_all = ['2','1','3b','3a','4','6mp','6d','6v','FEF','SCEF','6ma','24dd','24dv','23d','23c','p24pr','p32pr','55b','SFL','5m','5L','5mv']

#'PCV','7Am','31a','31pd'

"""
Plot Left
"""

overlay_gasnetDL = "/media/irebollo/storage/projects/Navigastric/scripts/bashScripts/freesurfer/warpGasnet/lh.gasnet.allSub_RF_ANTs_MNI152_orig_to_fsaverage.nii"
gasnetES_L = "/media/irebollo/storage/projects/Navigastric/ClusterResults/effecsizes/lh.cd.FUSPROJ.nii"


# overlay_gasnetDL = "/media/irebollo/storage/projects/Navigastric/scripts/bashScripts/freesurfer/warpGasnet/lh.gasnet.allSub_RF_ANTs_MNI152_orig_to_fsaverage.nii"
gasnet_l = io.read_scalar_data(overlay_gasnetDL)
gasnet_l[gasnet_l > 0.001] = 1


# gasnetES_L = "/media/irebollo/storage/projects/Navigastric/ClusterResults/effecsizes/lh.cd.allSub_RF_ANTs_MNI152_orig_to_fsaverage.nii"
sig1_l = io.read_scalar_data(gasnetES_L)
sig1_l[gasnet_l < 1 ] = 0

hemi="lh"


# labels = mne.read_labels_from_annot('/media/irebollo/storage/projects/Navigastric/freesurferData/fsaverage', parc='HCPMMP1', hemi=hemi)
labels = mne.read_labels_from_annot('/media/irebollo/storage/projects/Navigastric/freesurferData/fsaverage', parc='HCPMMP1', hemi=hemi)

labels = {l.name: l for l in labels}

####

brain = Brain(subject_id,hemi,surf,subjects_dir="/media/irebollo/storage/projects/Navigastric/freesurferData/",background="w")

    

V = brain.geo[hemi].x.size


LOI_l = [None] *len(LOS_all)
count=0
for name in LOS_all: 
    LOI_l[count] = 'L_'+LOS_all[count]+'_ROI-lh'
    count= count+1
    
data = np.zeros((V))
count=0
for name in LOI_l: 
    data[labels[name].vertices] = count+1
    count= count+1


#brain.add_data(data, min=1, max=count+1,thresh=1,colormap="RdBu", alpha=1, colorbar=False)

colors_all = ['green','green','green','green','blue','blue','blue','blue','blue','blue','blue','blue','blue','blueviolet','blueviolet','blueviolet','blueviolet','pink','blue','turquoise','turquoise','turquoise']

#colors_all = ['Red','darkred','darkred','darkred','lightcoral','chocolate','blue','blue','blue','royalblue','navy','navy','blueviolet','blueviolet','blueviolet','indigo','indigo','mediumpurple','darkgreen','darkgreen','darkgreen']

count=0
for name in LOS_all: 
    LOI_l = 'L_'+LOS_all[count]+'_ROI'
    label_name = LOI_l
    brain.add_label(label_name,borders=True,color=colors_all[count],alpha=0.85)
    count = count +1
    
    
count=0
for name in LOS_all: 
    LOI_l = 'L_'+LOS_all[count]+'_ROI'
    label_name = LOI_l
    brain.add_label(label_name,borders=3,color=colors_all[count],alpha=0.85)
    count = count +1
  

brain.add_data(sig1_l, min=0.3, max=0.5,thresh=0.001,colormap="autumn", alpha=1, colorbar=True)


brain.show_view(dict(azimuth=-10, elevation=-70, distance=400))
# brain.save_image("/media/irebollo/storage/projects/Navigastric/scripts/plots&figures/SMC_LL.png")

brain.show_view(dict(azimuth=0, elevation=65, distance=400))
# brain.save_image("/media/irebollo/storage/projects/Navigastric/scripts/plots&figures/SMC_LM.png")



##### Right hemisphere

overlay_gasnetDR = "/media/irebollo/storage/projects/Navigastric/scripts/bashScripts/freesurfer/warpGasnet/rh.gasnet.allSub_RF_ANTs_MNI152_orig_to_fsaverage.nii"
gasnetES_R = "/media/irebollo/storage/projects/Navigastric/ClusterResults/effecsizes/rh.cd.FUSPROJ.nii"


# overlay_gasnetDR = "/media/irebollo/storage/projects/Navigastric/scripts/bashScripts/freesurfer/warpGasnet/rh.gasnet.allSub_RF_ANTs_MNI152_orig_to_fsaverage.nii"
gasnet_r = io.read_scalar_data(overlay_gasnetDR)
gasnet_r[gasnet_r > 0.001] = 1


# gasnetES_R = "/media/irebollo/storage/projects/Navigastric/ClusterResults/effecsizes/rh.cd.allSub_RF_ANTs_MNI152_orig_to_fsaverage.nii"
sig1_r = io.read_scalar_data(gasnetES_R)
sig1_r[gasnet_r < 1 ] = 0

hemi="rh"
# labels = mne.read_labels_from_annot('/media/irebollo/storage/projects/Navigastric/freesurferData/fsaverage', parc='HCPMMP1', hemi=hemi)
labels = mne.read_labels_from_annot('/media/irebollo/storage/projects/Navigastric/freesurferData/fsaverage', parc='HCPMMP1', hemi=hemi)

labels = {l.name: l for l in labels}




LOI_r = [None] *len(LOS_all)
count=0
for name in LOS_all: 
    LOI_r[count] = 'R_'+LOS_all[count]+'_ROI-rh'
    count= count+1



brain = Brain(subject_id,hemi,surf,subjects_dir="/media/irebollo/storage/projects/Navigastric/freesurferData/",background="w")
V = brain.geo[hemi].x.size

data = np.zeros((V))
count=0
for name in LOI_r: 
    data[labels[name].vertices] = count+1
    count= count+1

#brain.add_data(data, min=1, max=count+1,thresh=1,colormap="RdBu", alpha=1, colorbar=False)


colors_all = ['green','green','green','green','blue','blue','blue','blue','blue','blue','blue','blue','blue','blueviolet','blueviolet','blueviolet','blueviolet','pink','blue','turquoise','turquoise','turquoise']

count=0
for name in LOS_all: 
    LOI_l = 'R_'+LOS_all[count]+'_ROI'
    label_name = LOI_l
    brain.add_label(label_name,borders=True,color=colors_all[count],alpha=0.85)
    count = count +1
    
    
# plot
    
brain.add_data(sig1_r, min=0.3, max=0.5,thresh=0.001,colormap="autumn", alpha=1, colorbar=True)


brain.show_view(dict(azimuth=10, elevation=70, distance=400))
# brain.save_image("/media/irebollo/storage/projects/Navigastric/scripts/plots&figures/SMC_RL.png")

brain.show_view(dict(azimuth=0, elevation=-65, distance=400))
# brain.save_image("/media/irebollo/storage/projects/Navigastric/scripts/plots&figures/SMC_RM.png")

brain.toggle_toolbars(True)

